# Generated by Django 4.1.5 on 2023-01-12 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, null=True)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
