# Generated by Django 4.1.5 on 2024-07-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=120, null=True)),
                ('price', models.PositiveIntegerField(default=0, null=True)),
                ('quantity', models.PositiveIntegerField(default=0, null=True)),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
                'ordering': ['-id'],
            },
        ),
    ]
